{
  lib,
  config,
  pkgs,
  tools,
  ...
}:

let
  shouldUsePcConfig = config.bobymoby.wayland.hyprland.usePcConfig;
  shouldUseLaptopConfig = config.bobymoby.wayland.hyprland.useLaptopConfig;
  configPath =
    if shouldUsePcConfig then
      ./specific/pc
    else if shouldUseLaptopConfig then
      ./specific/laptop
    else
      null;
  enabledTerminal = builtins.head (tools.getEnabledModules config.bobymoby.terminal);

  # Hyprland >= 0.55 reads ~/.config/hypr/hyprland.lua in preference to
  # hyprland.conf. We assemble the modular .lua sources into a single chunk so
  # `terminalClean` (declared once at the top) is visible to every module.
  specificLua =
    if shouldUsePcConfig then
      ''
        ${builtins.readFile ./specific/pc/hyprland.lua}
        ${builtins.readFile ./specific/pc/nvidia.lua}
      ''
    else if shouldUseLaptopConfig then
      builtins.readFile ./specific/laptop/hyprland.lua
    else
      "";

  hyprlandLua = ''
    -- Generated by Home Manager. Do not edit ~/.config/hypr/hyprland.lua directly;
    -- edit the .lua sources in home-modules/wayland/hyprland/ instead.

    local terminalClean = "${enabledTerminal}"

    ${builtins.readFile ./common/settings.lua}
    ${builtins.readFile ./common/input.lua}
    ${builtins.readFile ./common/binds.lua}
    ${builtins.readFile ./common/startup.lua}
    ${specificLua}
  '';
in
{
  options.bobymoby.wayland.hyprland = {
    enable = tools.mkEnableOption "Enable Hyprland";
    useLaptopConfig = tools.mkEnableOption "Use laptop configuration";
    usePcConfig = tools.mkEnableOption "Use PC configuration";
  };

  config = lib.mkIf config.bobymoby.wayland.hyprland.enable {
    assertions = [
      {
        assertion = !builtins.isNull configPath;
        message = "You have to specify which hyprland configuration to use";
      }
    ];
    home = {
      file = {
        #     ".config/hypr" = {
        #       source = configPath;
        #       recursive = true;
        #     };
        #     ".config/hypr/common" = {
        #       source = ./common;
        #       recursive = true;
        #     };
        #     ".config/hypr/common/hm.conf".text = ''
        #       $terminalClean = ${enabledTerminal}
        #     '';
        ".config/hypr/scripts" = {
          source = ./scripts;
          recursive = true;
        };
        ".config/hypr/assets" = {
          source = ./assets;
          recursive = true;
        };
        ".config/hypr/hyprlock.conf".source = configPath + "/hyprlock.conf";
        ".config/hypr/hypridle.conf".source = configPath + "/hypridle.conf";
        ".config/hypr/mocha.conf".source = ./common/mocha.conf;
        # ".config/hypr/hyprpaper.conf".source = ./extras/hyprpaper.conf;
        # ".config/hypr/hyprland.lua".text = hyprlandLua;
      };

      packages = with pkgs; [
        hyprshot
        hypridle
        hyprlock
        # hyprpaper
        awww
        cliphist
        wl-clipboard
      ];
    };
    wayland.windowManager.hyprland = {
      enable = true;
      plugins = with pkgs.hyprlandPlugins; [
        # hyprexpo
      ];
      configType = "lua";

      extraConfig = hyprlandLua;
      # The actual configuration lives in ~/.config/hypr/hyprland.lua (assembled
      # above and written via home.file). Hyprland >= 0.55 prefers the .lua entry
      # point over the hyprland.conf this module still generates.
    };
    # wayland.windowManager.hyprland = {
    #   enable = true;
    #   # plugins = with pkgs.hyprlandPlugins; [
    #   #   hy3
    #   # ];
    # };

    bobymoby = {
      wayland = {
        waybar = {
          enable = true;
          inherit (config.bobymoby.wayland.hyprland) useLaptopConfig usePcConfig;
        };
        rofi.enable = true;
      };
      notifications.dunst.enable = true;
    };

  };
}
